start = input('Podaj miasto A: ')
meta = input('Podaj miasto B: ')
dystans = float(input('Podaj dystans: '))
paliwo = float(input('Podaj cenę paliwa: '))
spalanie = float(input('Podaj spalanie auta: '))
koszt = int(dystans * spalanie * paliwo /100)
print(f'Miasto A {start}')
print(f'Miasto B {meta}')
print(f'Dystans {start} - {meta}: {dystans}')
print(f'Cena paliwa: {paliwo}')
print(f'Kosztprzejazdu: {start}-{meta} to {koszt:.2f}')